# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 192.168.1.131
  become: yes

  tasks:

- name: Call Roles
  hosts: 192.168.1.131
  roles:
   -role: motd
   #- firewalld
   #- ntp-config
   #- motd
   
